// <auto-generated />
namespace BulbDigitalChangelog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedurl));
        
        string IMigrationMetadata.Id
        {
            get { return "201701271631486_addedurl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
